# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('delivery_date', models.DateField()),
                ('product_id', models.TextField()),
                ('payment_option', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('order_status', models.CharField(max_length=50)),
            ],
        ),
    ]
